### ISSUE TITLE
Jobs tab namespace selection broken

### ISSUE THREAD

**Issue by rooty0** [volcano-sh/dashboard#159]
When switching to the **Jobs** tab, the namespace selection dropdown is no longer available - it's limited to the `default` namespace only.

![Image](https://github.com/user-attachments/assets/2754cd66-4aac-4cd8-9940-7e36c07bdfee)

This issue appears to be present on the `main` branch.
Per my investigation, the following PR seems to have introduced the regression: [[PR]](https://github.com/volcano-sh/dashboard/pull/80)

**Comment by JesseStutler** [comment]
@rooty0  Hi, how do you deploy the dashboard? Deploy the dashboard by yaml or by npm?

**Comment by rooty0** [comment]
@JesseStutler Sorry about the delay - I missed your message!

For building the images, I'm using [this](https://github.com/volcano-sh/dashboard/tree/v0.1.1/deployment/build).
Then for deployment, I'm using a slightly modified version of [this](https://github.com/volcano-sh/dashboard/blob/v0.1.1/deployment/volcano-dashboard.yaml)

I also test things locally with Docker Compose using something like this: 
```yaml
---
version: '3.8'

services:
  frontend:
    build:
      context: /Users/rooty/me/projects/dashboard-volcano
      dockerfile: /Users/rooty/me/projects/dashboard-volcano/deployment/build/frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    network_mode: "host"

  backend:
    build:
      context: /Users/rooty/me/projects/dashboard-volcano
      dockerfile: /Users/rooty/me/projects/dashboard-volcano/deployment/build/backend/Dockerfile
    volumes:
      - /Users/rooty/.kube/custom-kubeconfig.yaml:/root/.kube/config:ro
    environment:
      - KUBECONFIG=/root/.kube/config
    network_mode: "host"
```
